### ISSUE TITLE
Better Readme

### ISSUE THREAD

**Issue by hex-plex** [Raghav-Soni/Inverted-Pendulum-Model-Trajectory-For-Biped#1]
Add some visual element to it else it would be really underated, :raised_hands:  really awesome!! work man

**Comment by Raghav-Soni** [comment]
Thank You so much bro, will implement functions to change step length and direction dynamically, once I am able to make a robot walk with this in straight line. Will add visual elements to the readme, was thinking to plot some 3D graphs too but didn't get time for it. Thanks for the valuable suggestions... It means a lot that you gave it a look
